gems:
  - jekyll-sitemap

# Outputting
permalink: pretty

# custom vars
# excerpt: Simplify. Integrate. Track.  Simplify electronic proof of delivery (ePod), Integrate with existing systems easily, streamline vehicle transportation tracking,
excerpt: Simplified Vehicle Delivery... Integrated Mobile Solutions... Tracking System with Unlimited VINs...
url: http://vehichaul.com
